using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public static class GameStat
{
    public static Dictionary<CharacterName, string> characterTranslate = new Dictionary<CharacterName, string>()
    {
        { CharacterName.WeaponSkill,"Навык Рукопашной" },
        { CharacterName.BallisticSkill,"Навык Стрельбы" },
        { CharacterName.Strength,"Сила" },
        { CharacterName.Toughness,"Выносливость" },
        { CharacterName.Agility,"Ловкость" },
        { CharacterName.Intelligence,"Интеллект" },
        { CharacterName.Perception,"Восприятие" },
        { CharacterName.Willpower,"Сила Воли" },
        { CharacterName.Fellowship,"Общительность" },
        { CharacterName.Influence,"Влияние" }

    };

    public static Dictionary<Inclinations, string> inclinationTranslate = new Dictionary<Inclinations, string>()
    {
        {Inclinations.Agility, "Ловкость" },
        {Inclinations.Ballistic, "Стрельба" },
        {Inclinations.Defense, "Защита" },
        {Inclinations.Fellowship, "Общительность" },
        {Inclinations.Fieldcraft, "Полевое" },
        {Inclinations.Finesse, "Изящество" },
        {Inclinations.General, "Общее" },
        {Inclinations.Intelligence, "Интеллект" },
        {Inclinations.Knowledge, "Познание" },
        {Inclinations.Leadership, "Лидерство" },
        {Inclinations.Offense, "Нападение" },
        {Inclinations.Perception, "Восприятие" },
        {Inclinations.Psyker, "Псайкер" },
        {Inclinations.Social, "Общение" },
        {Inclinations.Strength, "Сила" },
        {Inclinations.Tech, "Тех" },
        {Inclinations.Toughness, "Выносливость" },
        {Inclinations.Weapon, "Ближний бой" },
        {Inclinations.Willpower, "Сила Воли" }
    };
    
    /*
    public static Dictionary<SkillName, string> skillTranslate = new Dictionary<SkillName, string>()
    {
        {SkillName.Acrobatics, "Акробатика" },
        {SkillName.Athletics, "Атлетика" },
        {SkillName.Awareness, "Бдительность" },
        {SkillName.Charm, "Обаяние" },
        {SkillName.Command, "Командование" },
        {SkillName.Commerce, "Коммерция" },
        {SkillName.Deceive, "Обман" },
        {SkillName.Dodge, "Уклонение" },
        {SkillName.Inquiry, "Дознание" },
        {SkillName.Interrogation, "Допрос" },
        {SkillName.Intimidate, "Запугивание" },
        {SkillName.Logic, "Логика" },
        {SkillName.Medicae, "Медика" },
        {SkillName.NavigateSurface, "Навигация(наземн)" },
        {SkillName.NavigateStellar, "Навигация(косм)" },
        {SkillName.NavigateWarp, "Навигация(варп)" },
        {SkillName.OperateAero, "Управление(аэро)" },
        {SkillName.OperateSurf, "Управление(наземн)" },
        {SkillName.OperateVoidship, "Управление(косм)" },
        {SkillName.Parry, "Парирование" },
        {SkillName.Psyniscience, "Психонаука" },
        {SkillName.Scrutiny, "Проницательность" },
        {SkillName.Security, "Безопасность" },
        {SkillName.SleightOfHand, "Ловкость рук" },
        {SkillName.Stealth, "Скрытность" },
        {SkillName.Survival, "Выживание" },
        {SkillName.TechUse, "Техпользование" },
        {SkillName.CommonLore, "Общие знания" },
        {SkillName.ForbiddenLore, "Запретные знания" },
        {SkillName.Linquistics, "Лингвистика" },
        {SkillName.ScholasticLore, "Ученые знания" },
        {SkillName.Trade, "Ремесло" },
    };

    public static Dictionary<KnowledgeName, string> knowledgeTranslation = new Dictionary<KnowledgeName, string>()
    {
        {KnowledgeName.Arheotech, "Археотех" },
        {KnowledgeName.AstartesOfChaos, "Космодесантники хаоса" },
        {KnowledgeName.CriminalForb, "Криминальные картели" },
        {KnowledgeName.Demonology, "Демонология" },
        {KnowledgeName.Heresy, "Ересь" },
        {KnowledgeName.HorusHeresyAndLongWar, "Ересь Хоруса и Долгая Война" },
        {KnowledgeName.Inquisition, "Инквизиция" },
        {KnowledgeName.Mutant, "Мутанты" },
        {KnowledgeName.OficioAssasinorum, "Официо Ассасинорум" },
        {KnowledgeName.Pirates, "Пираты" },
        {KnowledgeName.Psykers, "Псайкеры" },
        {KnowledgeName.Warp, "Варп" },
        {KnowledgeName.Xenos, "Ксеносы" },
        {KnowledgeName.RunesOfOrder, "Руны Ордена" },
        {KnowledgeName.MarkOfChaos, "Знаки Хаоса" },
        {KnowledgeName.EldariLingva, "Язык Эльдар" },
        {KnowledgeName.HighGhotic, "Высокий Готик" },
        {KnowledgeName.ImperialCodes, "Имперские Коды" },
        {KnowledgeName.Jargon, "Жаргон Наёмников" },
        {KnowledgeName.NecrontirLingva, "Некронтир" },
        {KnowledgeName.OrcsLingva, "Оркский" },
        {KnowledgeName.LingvaTechno, "Лингва-Техно" },
        {KnowledgeName.TauLingva, "Язык Тау" },
        {KnowledgeName.CriminalCodes, "Преступные шифры" },
        {KnowledgeName.MarkOfXenos, "Метки Ксеносов" },
        {KnowledgeName.Sororitas, "Адепта Сороритас" },
        {KnowledgeName.Arbitres, "Адептус Арбитрес" },
        {KnowledgeName.Astartes, "Адептус Астартес" },
        {KnowledgeName.AstraTelepatica, "Адептус Астра Телепатика" },
        {KnowledgeName.Mechanicus, "Адептус Механикус" },
        {KnowledgeName.Administratum, "Администратум" },
        {KnowledgeName.CapitanHartisti, "Капитаны-хартисты" },
        {KnowledgeName.KolegiaTitanika, "Коллегия Титаника" },
        {KnowledgeName.Eklezarkhia, "Экклезиархия" },
        {KnowledgeName.ImperialCredo, "Имперское Кредо" },
        {KnowledgeName.AstraMilitarum, "Астра Милитарум" },
        {KnowledgeName.ImperialFleet, "Имперский Флот" },
        {KnowledgeName.Imperium, "Империум" },
        {KnowledgeName.Navigators, "Навигаторы" },
        {KnowledgeName.Teroborona, "Силы Планетарной Обороны" },
        {KnowledgeName.RougeTrader, "Вольные Торговцы" },
        {KnowledgeName.ScholaProgenium, "Схола Прогениум" },
        {KnowledgeName.Techno, "Техно" },
        {KnowledgeName.Criminal, "Преступность" },
        {KnowledgeName.War, "Война" },
        {KnowledgeName.AgroTr, "Агро" },
        {KnowledgeName.ArcheologyTr, "Археолог" },
        {KnowledgeName.GunsmithTr, "Оружейник" },
        {KnowledgeName.AustroGraphTr, "Астрограф" },
        {KnowledgeName.ChymicTr, "Химик" },
        {KnowledgeName.CryptoTr, "Криптограф" },
        {KnowledgeName.CockTr, "Повар" },
        {KnowledgeName.ExploratorTr, "Эксплоратор" },
        {KnowledgeName.LingvistTr, "Лингвист" },
        {KnowledgeName.EpistolTr, "Эпистолярий" },
        {KnowledgeName.MortikatorTr, "Мортикатор" },
        {KnowledgeName.IpolnitelTr, "Исполнитель" },
        {KnowledgeName.GeologyTr, "Геолог" },
        {KnowledgeName.RezchikTr, "Резчик" },
        {KnowledgeName.SculptureTr, "Скульптор" },
        {KnowledgeName.KorabelTr, "Корабел" },
        {KnowledgeName.PredskazatelTr, "Предсказатель" },
        {KnowledgeName.TechnomantTr, "Техномант" },
        {KnowledgeName.PustoplavatelTr, "Пустоплаватель" },
        {KnowledgeName.Astromancy, "Астромансия" },
        {KnowledgeName.Beasts, "Звери" },
        {KnowledgeName.Burocracy, "Бюрократия" },
        {KnowledgeName.Chemistry, "Химия" },
        {KnowledgeName.Cryptology, "Криптология" },
        {KnowledgeName.Geraldica, "Геральдика" },
        {KnowledgeName.ImperialPatents, "Имперские Патенты" },
        {KnowledgeName.Justice, "Правосудие" },
        {KnowledgeName.Legends, "Легенды" },
        {KnowledgeName.Numerology, "Нумерология" },
        {KnowledgeName.Occultism, "Оккультизм" },
        {KnowledgeName.Phylosophy, "Философия" },
        {KnowledgeName.TacticImperialis, "Тактика Империалис" },
        {KnowledgeName.Askelon, "Аскелон" },
        {KnowledgeName.Ministorum, "Экклезиархия" }
    };*/
    public enum Inclinations {None, Agility, Ballistic, Defense, Fellowship,
    Fieldcraft, Finesse, General, Intelligence, Knowledge, Leadership,
    Offense, Perception, Psyker, Social, Strength, Tech, Toughness,
    Weapon, Willpower};

    public enum CharacterName { None, WeaponSkill, BallisticSkill, Strength, Toughness, Agility, Intelligence, Perception, Willpower, Fellowship, Influence}    
    
    public enum SkillName {None, Acrobatics, Athletics, Awareness, Charm, Command,
    Commerce, Deceive, Dodge, Inquiry, Interrogation, Intimidate, Logic,
    Medicae, NavigateSurface, NavigateStellar, NavigateWarp, OperateAero,
    OperateSurf, OperateVoidship, Parry, Psyniscience, Scrutiny, Security,
    SleightOfHand, Stealth, Survival, TechUse, CommonLore, ForbiddenLore, 
    Linquistics, ScholasticLore, Trade}

    public enum RoleName {None, Assasin, Hirurgion, Desperado, Ierofant, Mistic, Sage, Seeker, Warrior, 
    Fanatic, Kaushisa, Crusader, Ass}

    public static Dictionary<Inclinations, string> descriptionInclination = new Dictionary<Inclinations, string>()
    {
        {Inclinations.Agility, "Отображают способность персонажа повышать Ловкость, а также связанные с ней умения и таланты." },
        {Inclinations.Ballistic, "Отображают способность персонажа повышать Навык стрельбы, а также связанные с ней умения и таланты. " },
        {Inclinations.Defense, "Аколиты с этой склонностью быстро учатся выживать среди смертельного хаоса сражения. Являются ли они искусными обороняющимися или упрямыми крепышами, они выживают на полях сражений и в полных насилия подульях 41-ого тысячелетия, вымощенных костями более слабых. " },
        {Inclinations.Fellowship, "Отображают способность персонажа повышать Общительность, а также связанные с ней умения и таланты. " },
        {Inclinations.Fieldcraft, "Выжить на суровых просторах Империума порой не менее сложно чем в настоящем сражении. Аколиты со склонностью Полевое легко приспосабливаются и преуспевают в мириаде ситуаций, от душных джунглей, до унылых пустынь. " },
        {Inclinations.Finesse, "Умения и таланты со склонностью Изящество полагаются на безошибочное мастерство и тщательное планирование. Аколиты со склонностью Изящество могут стать экспертами в стрельбе на дальние дистанции или использовании экзотического оружия." },
        {Inclinations.General, "Общее" },
        {Inclinations.Intelligence, "Отображают способность персонажа повышать Интеллект, а также связанные с ней умения и таланты. " },
        {Inclinations.Knowledge, "Бесчисленные миры и колоссальные организации Империума накопили больше информации, чем возможно познать за миллион жизней. В то время как большинство подданных Императора остаются в неведении относительно великих и загадочных путей Империума, персонажи со склонностью Познание могут сравнительно легко получить доступ к информации." },
        {Inclinations.Leadership, "В Империуме живут несметные миллиарды людей, но без руководства они не более сильны, чем блеющие овцы или непослушные дети. Эффективное командование бесценно для защиты Человечества, и аколиты с этой склонностью способны превратить трясущихся от страха гражданских в мстительную армию готовую штурмовать еретическое капище или защищаться от ксеносов-налётчиков." },
        {Inclinations.Offense, "Персонажи с этой склонностью предпочитают использовать грубую силу вместо более тщательного, стратегического подхода. Эти аколиты часто бросаются в рукопашную охваченные безудержной яростью или разрывают врага превосходящей огневой мощью." },
        {Inclinations.Perception, "Отображают способность персонажа повышать Восприятие, а также связанные с ней умения и таланты. " },
        {Inclinations.Psyker, "Склонность Псайкер могут получить лишь обладающие редкой способностью владеть психическими силами. Также она указывает на способность ощущать сверхъестественные энергии, сигнализирующие о присутствии обитателей Варпа или использовании психических сил. " },
        {Inclinations.Social, "Обмен словами может быть не менее опасным, чем перестрелка, особенно для незнакомых с правилами и законами словесной войны. С этой склонностью легко выучить, как наилучшим образом использовать медоточивые речи и жёсткое запугивание для продуктивного общения с самонадеянными священниками, свободолюбивыми вольными торговцами и иными персонажами. " },
        {Inclinations.Strength, "Отображают способность персонажа повышать Силу, а также связанные с ней умения и таланты. " },
        {Inclinations.Tech, "Лишь немногие осмеливаются вмешиваться в работу мистических артефактов Тёмной Эры Технологий, и ещё меньше людей преуспевают в этом. Персонажи со склонностью Техно неспособны понять принципы работы машин, но легко общаются с их духами и способны получить результат там, где другие найдут лишь неудачу." },
        {Inclinations.Toughness, "Отображают способность персонажа повышать Выносливость, а также связанные с ней умения и таланты. " },
        {Inclinations.Weapon, "Отображают способность персонажа повышать Навык рукопашной, а также связанные с ней умения и таланты. " },
        {Inclinations.Willpower, "Отображают способность персонажа повышать Силу Воли, а также связанные с ней умения и таланты. " }
    };
}
